### ISSUE TITLE
Why is the program obstructed at 'worker = build_worker(cfg)'? It even takes 10+ hours without any response.

### ISSUE THREAD

**Issue by caixxuan** [autonomousvision/sledge#6]
Terminal shows:

![Screenshot from 2024-09-21 10-21-19](https://github.com/user-attachments/assets/49a545b3-29d9-49ec-b219-aaa7019d454c)

And there is no other response, even I have waited for 10+ hours, I have to stopped it. 

I can locate the code:

'worker = build_worker(cfg)' in run_autoencoder.py. this is the reason.

**Comment by caixxuan** [comment]
I change the worker to this:
worker: single_machine_thread_pool #caixuan

It can train properly!

**Comment by caixxuan** [comment]
But I  cannot monitor the run with tensorboard. http://localhost:6006/ seems cannot raise the tensorboard? Big thanks

**Comment by DanielDauner** [comment]
Hi

Both issues might be related since the ray library and tensorboard rely on local network services.

- The ray library is used in SLEDGE to paralyze (and speed up) the preprocessing and the simulation across threads in your system. You don't need it for training because [PyTorch's dataloader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) has its own multi-process methods implemented (i.e. by setting [`num_workers`](https://github.com/autonomousvision/sledge/blob/345a0c33e3a7b5e6aae9de37a6ff387ae3ab9402/sledge/script/config/autoencoder/data_loader/default_data_loader.yaml#L8). If you want to use simulation and preprocessing, we still recommend using the ray library because of significantly faster code execution. In your case, the initialization of ray workers appears to be interrupted in [this line](https://github.com/motional/nuplan-devkit/blob/cd3fd8d3d0c4d390fcb74d05fd56f92d9e0c366b/nuplan/planning/utils/multithreading/worker_ray.py#L78). Note that ray has a [dashboard](https://docs.ray.io/en/latest/cluster/configure-manage-dashboard.html) which uses the internal network.
 
- Tensorboard also uses local networking, typically with a `localhost` address and a default port number `6006`. Could you verify these are the designated values? Could you assign a different port number, i.e. by running `tensorboard --logdir ./path/to/logs --port 8080`?

The issues might be dependent on your system and settings. I have previously encountered similar problems (with multi-GPU training), where PyTorch's distributed training couldn't resolve local addresses correctly. Are you running the code on a remote machine, local machine, or cluster?

Best,
Daniel

**Comment by caixxuan** [comment]
> Hi
> 
> Both issues might be related since the ray library and tensorboard rely on local network services.
> 
> * The ray library is used in SLEDGE to paralyze (and speed up) the preprocessing and the simulation across threads in your system. You don't need it for training because [PyTorch's dataloader](https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader) has its own multi-process methods implemented (i.e. by setting [`num_workers`](https://github.com/autonomousvision/sledge/blob/345a0c33e3a7b5e6aae9de37a6ff387ae3ab9402/sledge/script/config/autoencoder/data_loader/default_data_loader.yaml#L8). If you want to use simulation and preprocessing, we still recommend using the ray library because of significantly faster code execution. In your case, the initialization of ray workers appears to be interrupted in [this line](https://github.com/motional/nuplan-devkit/blob/cd3fd8d3d0c4d390fcb74d05fd56f92d9e0c366b/nuplan/planning/utils/multithreading/worker_ray.py#L78). Note that ray has a [dashboard](https://docs.ray.io/en/latest/cluster/configure-manage-dashboard.html) which uses the internal network.
> * Tensorboard also uses local networking, typically with a `localhost` address and a default port number `6006`. Could you verify these are the designated values? Could you assign a different port number, i.e. by running `tensorboard --logdir ./path/to/logs --port 8080`?
> 
> The issues might be dependent on your system and settings. I have previously encountered similar problems (with multi-GPU training), where PyTorch's distributed training couldn't resolve local addresses correctly. Are you running the code on a remote machine, local machine, or cluster?
> 
> Best, Daniel

Thanks for your patient answer. I decide to solve this problem later. I have go along your instruction .md. But I got a new problem, that is, when I run "bash simple_simulation.sh", the simulation always fails:

![Screenshot from 2024-09-21 20-00-36](https://github.com/user-attachments/assets/795c1f62-9ab4-430f-b681-9ba6dc1bad8f)

and there is nothing in /exp/../simulation_log/PDMClosedPlanner/...

![Screenshot from 2024-09-21 20-01-04](https://github.com/user-attachments/assets/b55b6413-079f-4fdc-8e23-6568ca300595)

**Comment by DanielDauner** [comment]
Hi @caixxuan. At first glance, this looks like a bug. Does the error occur on all generated samples or only in a few scenarios?

Best,
Daniel

**Comment by caixxuan** [comment]
> all generated samples

It should all generated samples, because nothing in /exp/../simulation_log/PDMClosedPlanner/.../log/..., and when I run run_sledgeboard.py, no any scenarios appears.

**Comment by DanielDauner** [comment]
Does the error occur when running the simulation or the sledgeboard?

**Comment by caixxuan** [comment]
> Does the error occur when running the simulation or the sledgeboard?

The error in the picture is running the simulation, I think no any scenario appears when running run_sledgeboard.py  is related to the error.

**Comment by caixxuan** [comment]
> > Does the error occur when running the simulation or the sledgeboard?
> 
> The error in the picture is running the simulation, I think no any scenario appears when running run_sledgeboard.py is related to the error.

And I run it in my single PC. Any other config should be changed?

**Comment by DanielDauner** [comment]
Hi @caixxuan, sorry for the late reply! Is the issue still a problem?

**Comment by caixxuan** [comment]
> Hi @caixxuan, sorry for the late reply! Is the issue still a problem?

Yes, I have not solve it now, Did I need to change any configurations on my single PC except: worker: single_machine_thread_pool ?

**Comment by DanielDauner** [comment]
So, currently, the issue(s) breaks down to 

1. Errors when using `worker=ray_distributed`.
2. Errors in the simulation, i.e. when propagating the agents.
3. Errors in sledgeboard, i.e. no scenarios.

Maybe for (1) you could try the following in [this issue](https://github.com/autonomousvision/tuplan_garage/issues/6#issuecomment-1756003829). That fix previously worked for me when running `ray` on a slurm cloud. (2) is a bug, which I will try to fix in an upcoming release. The problem (3) might be related to the failures in the simulation. Nevertheless, I previously had problems when visualizing simulation folders in the cloud from a local computer (i.e. with a mounted directory). This only worked if the folder path was equal on the cloud and mounted directory. 

I hope that helps!
Daniel

**Comment by caixxuan** [comment]
> So, currently, the issue(s) breaks down to
> 
>     1. Errors when using `worker=ray_distributed`.
> 
>     2. Errors in the simulation, i.e. when propagating the agents.
> 
>     3. Errors in sledgeboard, i.e. no scenarios.
> 
> 
> Maybe for (1) you could try the following in [this issue](https://github.com/autonomousvision/tuplan_garage/issues/6#issuecomment-1756003829). That fix previously worked for me when running `ray` on a slurm cloud. (2) is a bug, which I will try to fix in an upcoming release. The problem (3) might be related to the failures in the simulation. Nevertheless, I previously had problems when visualizing simulation folders in the cloud from a local computer (i.e. with a mounted directory). This only worked if the folder path was equal on the cloud and mounted directory.
> 
> I hope that helps! Daniel

thanks a lot, i will try it again

**Comment by DanielDauner** [comment]
I am closing this issue for now. Feel free to re-open the issue (or open a new one), if you have further questions!

Best
Daniel
